// RustyNES Android — Gradle settings (v1.8.0 "Android", Workstream A).
//
// This module wraps the pure-Rust workspace: the `.so` libraries are produced by
// `cargo-ndk` (see `app/build.gradle.kts`) and the Kotlin bindings to the
// `rustynes-mobile` control surface are generated by UniFFI. The module is
// intentionally self-contained so the Rust CI (host gates + the Android
// cross-build) and the Gradle CI (`bundleRelease`) stay independent.

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RustyNES"
include(":app")
