// RustyNES Android — Gradle settings (v1.8.0 "Android", Workstream A).
//
// This module wraps the pure-Rust workspace: the `.so` libraries are produced by
// `cargo-ndk` (see `app/build.gradle.kts`) and the Kotlin bindings to the
// `rustynes-mobile` control surface are generated by UniFFI. The module is
// intentionally self-contained so the Rust CI (host gates + the Android
// cross-build) and the Gradle CI (`bundleRelease`) stay independent.

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // v2.0.3 "Harbor" (ADR 0025): AppLovin MAX (the `play`-flavor ad mediation SDK,
        // AdGate / RewardedGate) is published on AppLovin's own Maven repository, not
        // Maven Central. `content { includeGroup(...) }` scopes it to the AppLovin group
        // only, so every other artifact still resolves from google()/mavenCentral() and
        // the clean `foss` variant — which never references `com.applovin.*` — pulls
        // nothing from here. RevenueCat (com.revenuecat.purchases) is on Maven Central.
        maven {
            url = uri("https://artifacts.applovin.com/android")
            content { includeGroup("com.applovin") }
        }
    }
}

rootProject.name = "RustyNES"
include(":app")
// v1.8.8 "Atlas" (Workstream J): the Macrobenchmark module that generates the
// Baseline + Startup Profiles (and the startup/jank benchmarks). A
// `com.android.test` module targeting :app; it is built/run on a device or AVD
// (`./gradlew :app:generateReleaseBaselineProfile`), never on the host CI path.
include(":baselineprofile")
