// RustyNES Android — Gradle settings (v1.8.0 "Android", Workstream A).
//
// This module wraps the pure-Rust workspace: the `.so` libraries are produced by
// `cargo-ndk` (see `app/build.gradle.kts`) and the Kotlin bindings to the
// `rustynes-mobile` control surface are generated by UniFFI. The module is
// intentionally self-contained so the Rust CI (host gates + the Android
// cross-build) and the Gradle CI (`bundleRelease`) stay independent.

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RustyNES"
include(":app")
// v1.8.8 "Atlas" (Workstream J): the Macrobenchmark module that generates the
// Baseline + Startup Profiles (and the startup/jank benchmarks). A
// `com.android.test` module targeting :app; it is built/run on a device or AVD
// (`./gradlew :app:generateReleaseBaselineProfile`), never on the host CI path.
include(":baselineprofile")
