#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Type-check rustynes-ios's iOS-only modules on a Linux (or macOS) host.
#
# `audio.rs`, `ffi.rs` and `gfx_metal.rs` are `#[cfg(target_os = "ios")]`, and
# nothing on a pull request builds the iOS target (only the tag-triggered
# `ios.yml` does, and it needs an Apple SDK for the vendored C). So a change to
# the C-ABI shim or the CoreAudio sink was first compiled at release time. This
# script closes most of that gap (v2.7.4): it generates a throwaway crate that
# includes the REAL `audio_dsp.rs`, `audio_ring.rs`, `audio.rs` and `ffi.rs` via
# `#[path]`, compiles `audio.rs` against the real cpal (whose API is the same on
# every backend), and stubs only `gfx_metal` -- the wgpu/Metal surface, which
# genuinely needs iOS. It then runs the crate's tests, including one that calls
# a wrapped FFI entry.
#
# What it does NOT check: `gfx_metal.rs`, and anything the iOS cpal backend or
# the Swift side does at runtime.
#
# Usage: scripts/ios-host-typecheck.sh   (from anywhere; exits non-zero on failure)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS="${ROOT}/crates/rustynes-ios/src"
WORK="${ROOT}/target/ios-host-typecheck"
mkdir -p "${WORK}/src"

# cpal is pinned to the same major the iOS crate uses.
CPAL_REQ="$(sed -n 's/^cpal = "\(.*\)"$/\1/p' "${ROOT}/crates/rustynes-ios/Cargo.toml")"
if [ -z "${CPAL_REQ}" ]; then
    echo "ios-host-typecheck: could not read the cpal version from crates/rustynes-ios/Cargo.toml" >&2
    exit 1
fi

cat > "${WORK}/Cargo.toml" <<EOF
[package]
name = "ios-host-typecheck"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rustynes-mobile = { path = "${ROOT}/crates/rustynes-mobile" }
log = "0.4"
cpal = "${CPAL_REQ}"
EOF

cat > "${WORK}/src/lib.rs" <<EOF
//! Generated by scripts/ios-host-typecheck.sh -- do not edit.
#![allow(dead_code, unsafe_code, clippy::all)]
#[path = "${IOS}/audio_dsp.rs"]
pub mod audio_dsp;
#[path = "${IOS}/audio_ring.rs"]
pub mod audio_ring;
#[path = "${IOS}/audio.rs"]
pub mod audio;
/// Stub: the wgpu/Metal renderer is the one module that genuinely needs iOS.
/// Its signatures mirror \`crates/rustynes-ios/src/gfx_metal.rs\`; a change
/// there that \`ffi.rs\` depends on must be mirrored here.
pub mod gfx_metal {
    use core::ffi::c_void;
    pub struct MetalGfx(Vec<u8>);
    impl MetalGfx {
        pub fn new(_v: *mut c_void, _w: u32, _h: u32) -> Result<Self, String> { Ok(Self(vec![0; 4])) }
        pub fn resize(&mut self, _w: u32, _h: u32) {}
        pub fn set_filter(&mut self, _f: u8, _p: [f32; 4]) {}
        pub fn frame_buf_mut(&mut self) -> &mut [u8] { &mut self.0 }
        pub fn set_index_frame(&mut self, _b: &[u8], _p: u8) {}
        pub fn render(&mut self) {}
        pub fn render_hd(&mut self, _fb: &[u8], _w: u32, _h: u32) {}
    }
}
#[path = "${IOS}/ffi.rs"]
pub mod ffi;

#[cfg(test)]
mod tests {
    #[test]
    fn a_wrapped_ffi_entry_runs() {
        // SAFETY: a null view is fine for the stub renderer; the handle is
        // destroyed once, below.
        let p = unsafe { super::ffi::rustynes_ios_gfx_init(core::ptr::null_mut(), 1, 1) };
        assert!(!p.is_null());
        // SAFETY: \`p\` is the live handle created above, not used after.
        unsafe { super::ffi::rustynes_ios_gfx_destroy(p) };
        // SAFETY: a null handle is the documented no-op case.
        assert_eq!(unsafe { super::ffi::rustynes_ios_audio_is_invalid(core::ptr::null_mut()) }, 0);
    }
}
EOF

cd "${WORK}"
CARGO_TARGET_DIR="${WORK}/target" cargo test --quiet
echo "ios-host-typecheck: audio_dsp, audio_ring, audio and ffi compile and pass on the host"
