import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    // v1.8.8 "Atlas": AGP 9 supplies Kotlin itself (built-in Kotlin), so the
    // standalone `org.jetbrains.kotlin.android` plugin is no longer applied. The
    // Compose compiler plugin remains a separate, explicitly versioned plugin.
    id("org.jetbrains.kotlin.plugin.compose")
    // v1.8.8 "Atlas" (Workstream J): consume + bundle the Baseline/Startup Profile
    // generated by the :baselineprofile module into assets/dexopt/baseline.prof.
    id("androidx.baselineprofile")
}

// The pure-Rust workspace lives one directory up from this Gradle module.
val workspaceRoot: File = rootDir.parentFile
// Where `cargo-ndk` writes the per-ABI `.so` files and where UniFFI writes the
// generated Kotlin bindings (added to the main source set below).
val jniLibsDir: File = file("src/main/jniLibs")
val uniffiGenDir: File = layout.buildDirectory.dir("generated/uniffi").get().asFile

// ABIs cross-compiled by cargo-ndk (the jniLibs always contain both): arm64 for
// devices, x86_64 for the emulator / CI smoke test. The *release* variant then
// packages arm64 only (smallest AAB — see the `release` buildType's abiFilters);
// the *debug* variant keeps x86_64 so it runs on the emulator. armeabi-v7a is
// opt-in (see the maintainer defaults).
val builtAbis = listOf("arm64-v8a", "x86_64")
val shipAbi = "arm64-v8a"

android {
    namespace = "com.doublegate.rustynes"
    // v1.8.8 "Atlas" (Workstream A): Android 16 QPR (API 37). The Play mandate
    // requires new submissions/updates to target Android 16 (API 36) after
    // 2026-08-31; we compile against the newer 37 SDK (AGP 9.2 supports it) so the
    // latest AndroidX (core 1.19 / lifecycle 2.11, which require compileSdk 37) link.
    compileSdk = 37

    defaultConfig {
        applicationId = "com.doublegate.rustynes"
        minSdk = 26 // AAudio floor.
        targetSdk = 36 // Play mandate (Android 16) from 2026-08-31.
        // v2.0.2 was a desktop-only PPU/AccuracyCoin cut, so the Android host stayed at
        // 20001/"2.0.1"; v2.0.3 bumped it to 20003. v2.0.4 "Harbor" is the Android
        // release-candidate cut (release signing scaffold + crash/ANR hardening +
        // fastlane listing metadata + version bump) on the byte-identical v2.0.3 core,
        // so the host advances 20003 -> 20004. The monotonic versionCode is the Play
        // upload ordinal; the internal/closed testing (RC) track uploads this AAB.
        versionCode = 20004
        versionName = "2.0.4"
        // No abiFilters here — set per buildType so release ships arm64 only
        // while debug keeps x86_64 for the emulator.
        // PLAY_BUILD is set per-flavor below (`false` for `foss`, `true` for `play`),
        // so the channel is a compile-time property. RustyNES is permanently
        // open-source and income-free, so this flag NO LONGER gates any monetization —
        // it only distinguishes the Play-services channel for the non-billing helpers
        // (e.g. PlayUpdates skips its in-app update/review work on the `foss` channel).
        // CHROMECAST_ENABLED gates the experimental Cast Application Framework
        // (CAF) sender path (v1.8.7, #38) — a ~20-30fps SPECTATOR mirror to a
        // custom Web Receiver, distinct from the primary low-latency Presentation
        // API cast (Cast.kt, which is always available). Default false: no Cast
        // button, no CastContext init, zero behavior change. It stays off until the
        // maintainer does the deferred ops (a $5 Cast Developer Console account, a
        // registered Receiver App ID, and HTTPS hosting of android/cast-receiver/).
        // See android/cast-receiver/README.md + ChromecastSender.kt.
        buildConfigField("boolean", "CHROMECAST_ENABLED", "false")
        // v1.8.8 "Atlas" (Workstreams D+E): Play Games Services v2 — cloud-save
        // Snapshots (D) + PGS achievements/leaderboards (E). Default false: no PGS
        // sign-in, no Snapshots/Achievements calls, zero behavior change. The deps
        // link but stay dormant until the maintainer creates the linked Play Games
        // project (game_ids / OAuth client) + the achievement/leaderboard IDs in the
        // Play Console and flips this on. DISTINCT from RetroAchievements (rustynes-ra,
        // v1.8.6) which stays untouched. See CloudSave.kt + PlayGames.kt.
        buildConfigField("boolean", "PGS_ENABLED", "false")
        // v1.8.8 "Atlas" (Workstream L): Play Integrity anti-tamper layer. Default
        // false: no token request, no verdict handling, zero behavior change. The
        // verdict DECRYPTION requires a linked Google Cloud project + a server endpoint
        // (maintainer ops), so the on-device handler is a documented stub until that
        // lands. See Integrity.kt.
        buildConfigField("boolean", "PLAY_INTEGRITY_ENABLED", "false")
        // v1.8.8 "Atlas" (Workstream L): the maintainer's linked Google Cloud project
        // NUMBER for Play Integrity's PrepareIntegrityTokenRequest. 0L = unset (the
        // Integrity client no-ops even if PLAY_INTEGRITY_ENABLED were on without it).
        buildConfigField("long", "INTEGRITY_CLOUD_PROJECT_NUMBER", "0L")
    }

    // v2.0.1 (ADR 0025): the `distribution` product-flavor split. Two channels off
    // the one byte-identical Timebase core. RustyNES is permanently open-source and
    // income-free — there is NO billing, NO ads, and NO tracking in either channel;
    // the split now distinguishes only the non-monetization Google Play services.
    //   - `foss` (default) — the pure-Rust emulator ONLY: no Google Play SDKs. This is
    //     the F-Droid + GitHub-Releases sideload artifact. Its `src/foss/` source set
    //     supplies no-op façades for every proprietary subsystem so `MainActivity`
    //     links without any `com.google.*` dependency (moved to `playImplementation`).
    //   - `play` — the optional Google Play services (Cast framework, Play Games v2,
    //     Play Integrity, in-app update/review, cloud save), all free. Google Play only.
    // PLAY_BUILD is set per-flavor; the per-feature runtime gates (PGS_ENABLED, …)
    // stay in defaultConfig as the in-`play` toggles the maintainer flips at launch.
    flavorDimensions += "distribution"
    productFlavors {
        create("foss") {
            dimension = "distribution"
            isDefault = true
            buildConfigField("boolean", "PLAY_BUILD", "false")
        }
        create("play") {
            dimension = "distribution"
            buildConfigField("boolean", "PLAY_BUILD", "true")
        }
    }

    // Release signing reads `keystore.properties` (gitignored) or env vars; when
    // neither is present the release build stays unsigned so CI `bundleRelease`
    // still links and verifies. Play App Signing manages the app key; this is the
    // upload key only.
    val keystorePropsFile = rootProject.file("keystore.properties")
    // CI / automated signing: the same four values via env vars (e.g. GitHub Actions
    // secrets) when the gitignored file isn't present. `RUSTYNES_UPLOAD_STORE_FILE`
    // gates it; the others are read only when it is set.
    val keystoreEnvFile = System.getenv("RUSTYNES_UPLOAD_STORE_FILE")
    signingConfigs {
        create("upload") {
            if (keystorePropsFile.exists()) {
                val props = Properties().apply { load(FileInputStream(keystorePropsFile)) }
                storeFile = file(props.getProperty("storeFile"))
                storePassword = props.getProperty("storePassword")
                keyAlias = props.getProperty("keyAlias")
                keyPassword = props.getProperty("keyPassword")
            } else if (keystoreEnvFile != null) {
                storeFile = file(keystoreEnvFile)
                storePassword = System.getenv("RUSTYNES_UPLOAD_STORE_PASSWORD")
                keyAlias = System.getenv("RUSTYNES_UPLOAD_KEY_ALIAS")
                keyPassword = System.getenv("RUSTYNES_UPLOAD_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // The shipped AAB carries arm64 only (smallest download).
            // v1.8.8 "Atlas" (Workstream J): upload a SYMBOL_TABLE of the Rust `.so` to
            // Play so native crash stacks (the cdylib) symbolicate. SYMBOL_TABLE (not
            // FULL) keeps the symbol upload well under Play's ~300 MB cap for a fat-LTO
            // Rust core while still giving readable function names. The packaged `.so`
            // itself stays stripped (R8 never touches it; only the symbol file is uploaded).
            ndk {
                abiFilters += shipAbi
                debugSymbolLevel = "SYMBOL_TABLE"
            }
            // v2.0.4 "Harbor" (Android RC): wire the release signing config with a
            // graceful debug-signing fallback. When the upload keystore is present
            // (maintainer secret — a `keystore.properties` file or the
            // `RUSTYNES_UPLOAD_*` env vars, both gitignored / injected in CI), sign the
            // release with the real upload key so the produced AAB is store-uploadable.
            // When ABSENT (a keyless CI or local RC build, which is the state on this
            // host), fall back to the debug signing config instead of leaving the build
            // UNSIGNED — an unsigned release APK cannot be `adb install`-ed, so a
            // maintainer smoke-testing `assembleFossRelease` without the secret would be
            // blocked. Debug-signed is never shippable (Play App Signing rejects the
            // debug key), so this fallback only ever produces a locally-installable RC
            // artifact; the real keystore path is what a store upload uses. See the
            // `signingConfigs { create("upload") }` block above for the credential
            // resolution order.
            signingConfig = if (keystorePropsFile.exists() || keystoreEnvFile != null) {
                signingConfigs.getByName("upload")
            } else {
                signingConfigs.getByName("debug")
            }
        }
        debug {
            applicationIdSuffix = ".debug"
            // Debug keeps x86_64 too so it installs on the emulator / CI.
            ndk { abiFilters += builtAbis }
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true // exposes BuildConfig.DEBUG for the debug-only ROM autoload.
    }

    // v1.8.8 "Atlas" (Workstream B): auto-generate the per-app `locales_config.xml`
    // from the `values-*` resource folders and reference it in the merged manifest
    // (so the system Settings -> Apps -> RustyNES -> Language entry appears on
    // Android 13+). AGP reads `res/resources.properties` (unqualifiedResLocale=en) to
    // know the default `values/` locale, and the `values-es/` folder to add Spanish.
    // The in-app picker (AppCompatDelegate.setApplicationLocales) back-ports the same
    // selection to API 24+ via androidx.appcompat below.
    androidResources {
        generateLocaleConfig = true
    }

    // The UniFFI-generated bindings are Kotlin (.kt). Under AGP 9's built-in Kotlin,
    // generated Kotlin sources must be registered on the source set's `kotlin`
    // directories — adding them to `.java` (the pre-AGP-9 way) no longer feeds the
    // Kotlin compiler, so the binding types (NesController, NpStatus, …) go
    // unresolved. See AGP 9 built-in-Kotlin migration notes.
    // `srcDir(Any)` is deprecated in AGP 9 in favour of the `directories`
    // mutable set. Verified against the interface rather than the warning text:
    // `AndroidSourceDirectorySet.getDirectories()` returns `Set<String>`, so it
    // takes PATHS, not `File`s -- hence `.path` on both.
    sourceSets["main"].kotlin.directories.add(uniffiGenDir.path)
    sourceSets["main"].jniLibs.directories.add(jniLibsDir.path)

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // 16 KB page alignment (Play requirement for Android 15+). NDK r27+ aligns
    // by default; AGP packages the aligned `.so` unchanged.
    packaging {
        jniLibs { useLegacyPackaging = false }
    }

    // v1.8.8 "Atlas" (Workstream J): keep all language resources in the base APK split
    // (no per-language AAB split). The in-app EN/ES picker
    // (AppCompatDelegate.setApplicationLocales, Workstream B) can select a locale whose
    // resources Play might otherwise have split out and not yet delivered — disabling
    // the language split guarantees every bundled locale is always present (no
    // missing-resource crash). The two-locale footprint cost is negligible.
    bundle {
        language { enableSplit = false }
    }
}

// Built-in Kotlin (AGP 9): the old `android.kotlinOptions { jvmTarget }` DSL moved
// to the top-level `kotlin.compilerOptions` block. The target defaults to
// `compileOptions.targetCompatibility` (17 above); set it explicitly for clarity.
kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

// v1.8.8 "Atlas" (Workstream J): Compose compiler stability metrics + reports.
// Opt-in via `-Pcompose.metrics` (kept off the default build so it doesn't slow
// every compile). When set, the Compose compiler emits per-composable skippability
// / restartability metrics and an unstable-class report under
// build/compose-metrics + build/compose-reports — run a RELEASE build with the flag
// in CI to flag any non-skippable composable (e.g. a List<> param read as unstable).
//   ./gradlew :app:assembleRelease -Pcompose.metrics
composeCompiler {
    if (project.hasProperty("compose.metrics")) {
        metricsDestination.set(layout.buildDirectory.dir("compose-metrics"))
        reportsDestination.set(layout.buildDirectory.dir("compose-reports"))
    }
}

// --- Rust integration -------------------------------------------------------

// Build the workspace `.so` libraries for every shipped ABI via cargo-ndk and
// drop them into `jniLibs/<abi>/`. Requires the Android Rust targets + cargo-ndk
// (`rustup target add aarch64-linux-android x86_64-linux-android;
//   cargo install cargo-ndk`) and ANDROID_NDK_HOME (or an SDK-resolved NDK).
val cargoNdkBuild = tasks.register<Exec>("cargoNdkBuild") {
    group = "rust"
    description = "Cross-compile rustynes-mobile + rustynes-android into jniLibs via cargo-ndk."
    workingDir = workspaceRoot
    val abiArgs = builtAbis.flatMap { listOf("-t", it) }
    commandLine(
        listOf("cargo", "ndk") + abiArgs +
            listOf(
                "-o", jniLibsDir.absolutePath,
                "--platform", "26",
                "build", "--release",
                "-p", "rustynes-mobile",
                "-p", "rustynes-android",
            ),
    )
}

// Generate the Kotlin bindings from the compiled arm64 cdylib (the UniFFI API is
// target-independent, so any built library serves as the source of truth).
val uniffiBindgen = tasks.register<Exec>("uniffiBindgen") {
    group = "rust"
    description = "Generate Kotlin bindings for the rustynes-mobile control surface via UniFFI."
    dependsOn(cargoNdkBuild)
    workingDir = workspaceRoot
    val lib = workspaceRoot.resolve("target/aarch64-linux-android/release/librustynes_mobile.so")
    commandLine(
        "cargo", "run", "-q", "-p", "rustynes-mobile", "--bin", "uniffi-bindgen", "--",
        "generate", "--library", lib.absolutePath,
        "--language", "kotlin", "--out-dir", uniffiGenDir.absolutePath,
    )
}

tasks.named("preBuild") { dependsOn(uniffiBindgen) }

dependencies {
    // v1.8.8 "Atlas": Compose BOM 2025.09.01 (material3 1.4.0 — the stable M3 set
    // for the launch; M3 Expressive's spring-physics/wavy components live in the
    // 1.5.0-alpha line and are deliberately not pulled in here). Bumped from
    // 2024.12.01 so the adaptive APIs (Window Size Classes, ListDetailPaneScaffold)
    // and a current Compose runtime are available.
    val composeBom = platform("androidx.compose:compose-bom:2026.08.00")
    implementation(composeBom)
    implementation("androidx.core:core-ktx:1.19.0")
    // v1.8.8 "Atlas" (Workstream B): per-app language. AppCompat 1.6.0+ supplies the
    // back-compat AppCompatDelegate.setApplicationLocales (delegating to the platform
    // LocaleManager on API 33+, and a manual override on API 24..32). MainActivity must
    // extend AppCompatActivity and the launch theme must derive from an AppCompat theme
    // for the locale APIs to take effect under Compose.
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.11.0")
    // collectAsStateWithLifecycle for the controller-connect StateFlow (v1.8.7, #41).
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.11.0")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    // v1.8.8 "Atlas" (Workstream A): adaptive layouts. `adaptive` carries
    // currentWindowAdaptiveInfoV2()/WindowSizeClass (the single layout driver);
    // -layout carries ListDetailPaneScaffold; -navigation carries the predictive-
    // back-aware NavigableListDetailPaneScaffold for the expanded two-pane.
    implementation("androidx.compose.material3.adaptive:adaptive:1.3.0")
    implementation("androidx.compose.material3.adaptive:adaptive-layout:1.3.0")
    implementation("androidx.compose.material3.adaptive:adaptive-navigation:1.3.0")
    // WindowInfoTracker / FoldingFeature for foldable-posture awareness.
    implementation("androidx.window:window:1.5.1")
    // v1.8.8 "Atlas" (Workstream K): Android-12+ system splash via the back-compat
    // SplashScreen API (installSplashScreen() before super.onCreate()).
    implementation("androidx.core:core-splashscreen:1.2.0")
    // v1.8.8 "Atlas" (Workstream C): async image loading + caching for the box-art
    // library grid. Coil 3 (io.coil-kt.coil3) loads local `content://`/`file://` URIs
    // through Android's ContentResolver WITHOUT any network artifact, so we add only
    // `coil-compose` (the core + the AsyncImage composable). The libretro box-art
    // auto-match (BoxArt.kt) does its own one-shot HttpURLConnection download to a
    // file:// cache, so no Coil network fetcher (coil-network-*) is pulled in either.
    implementation("io.coil-kt.coil3:coil-compose:3.5.0")
    // v1.8.8 "Atlas" (Workstream H): the home-screen "Resume <last game>" widget is
    // authored with Glance (Compose-idiomatic, matching the rest of the app). 1.3.0-
    // alpha01 is the Glance line that explicitly bumped its Compose compileSdk to API
    // 37 / AGP 9.2 — the exact toolchain this module uses (compileSdk 37, AGP 9) — so
    // the 1.1.x/1.2.x stable lines (compileSdk 34/35) would mismatch the build's
    // newer Compose runtime. glance-appwidget pulls glance + the AppWidget host glue.
    implementation("androidx.glance:glance-appwidget:1.3.0-alpha01")
    implementation("androidx.glance:glance-material3:1.3.0-alpha01")
    // v1.8.8 "Atlas" (Workstream J): persistent immutable collections. Lists handed
    // to Compose (the library grid entries/folders) become `ImmutableList`/`PersistentList`
    // so the compiler treats them as STABLE and the strong-skipping pass can skip the
    // list composables when the reference is unchanged — a `List<>` is inferred unstable.
    implementation("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.5.0")
    // v1.8.8 "Atlas" (Workstream J): installs the bundled Baseline Profile at runtime
    // (the AOT-compile hint for the launch/scroll classes). Pinned to the androidx.benchmark
    // 1.4.1 line that the :baselineprofile generator + the baselineprofile plugin use.
    implementation("androidx.profileinstaller:profileinstaller:1.4.1")
    // UniFFI's generated Kotlin loads the cdylib through JNA; the `@aar`
    // classifier pulls the Android-native JNA dispatcher.
    implementation("net.java.dev.jna:jna:5.19.1@aar")
    // v2.0.1 (ADR 0025): the optional Google Play services below are PLAY-FLAVOR ONLY.
    // `playImplementation` keeps these proprietary Google-Play SDKs out of the `foss`
    // (F-Droid/sideload) artifact entirely — the `foss` variant links none of them (its
    // `src/foss/` no-op façades stand in), so the clean channel has no Play Services.
    // RustyNES carries no billing and no ads in either channel.
    // Cast Application Framework sender (v1.8.7, #38). Linked but DORMANT: it does
    // nothing until CastContext is initialized, which only happens behind the
    // default-off BuildConfig.CHROMECAST_ENABLED flag (see ChromecastSender.kt).
    "playImplementation"("com.google.android.gms:play-services-cast-framework:22.1.0")
    // v1.8.8 "Atlas" (Workstreams D+E): Play Games Services v2 — the cloud-save
    // Snapshots client (D), the PGS achievements + leaderboards clients (E), and the
    // PGS v2 auto-sign-in (GamesSignInClient). 21.0.0 is the current v2 SDK (the v1
    // SDK is end-of-life). Linked but DORMANT: nothing initializes PlayGames until
    // behind the default-off BuildConfig.PGS_ENABLED flag (see CloudSave.kt /
    // PlayGames.kt). DISTINCT from RetroAchievements (rustynes-ra). The PGS sign-in
    // also reads the manifest <meta-data app_id>, which is a maintainer-supplied
    // placeholder (@string/game_services_project_id) until the Play Games project lands.
    "playImplementation"("com.google.android.gms:play-services-games-v2:22.0.0")
    // v1.8.8 "Atlas" (Workstream L): Play Integrity API — the anti-tamper layer. 1.6.0
    // (SafetyNet Attestation was turned down Jan 2025; this is the modern replacement).
    // Linked but DORMANT: no token is requested until behind the default-off
    // BuildConfig.PLAY_INTEGRITY_ENABLED flag (see Integrity.kt). Verdict decryption
    // needs the maintainer's linked Cloud project + server endpoint.
    "playImplementation"("com.google.android.play:integrity:1.6.0")
    // v1.8.8 "Atlas" (Workstream L): in-app updates (flexible) + in-app review. 2.1.0
    // is the in-app-update floor for targeting Android 14+; review 2.0.2 is current.
    // These need NO Cloud project — they no-op gracefully on a sideloaded (non-Play)
    // install, so they are safe to call unconditionally (still flavor-gated for clarity).
    "playImplementation"("com.google.android.play:app-update-ktx:2.1.0")
    "playImplementation"("com.google.android.play:review-ktx:2.0.2")
    // v1.8.8 "Atlas" (Workstream J): pull the generated Baseline + Startup Profiles
    // from the Macrobenchmark module. The baselineprofile plugin wires the produced
    // `baseline-prof.txt` / `startup-prof.txt` into this variant's merged assets.
    baselineProfile(project(":baselineprofile"))
}

// v1.8.8 "Atlas" (Workstream J): how :app consumes the generated profile.
//   - automaticGenerationDuringBuild = false: a normal `assembleRelease` does NOT
//     try to spin up a device to (re)generate — it just bundles whatever profile the
//     :baselineprofile module last produced (committed). The maintainer regenerates
//     on demand with `./gradlew :app:generateReleaseBaselineProfile` on a device/AVD.
//   - dexLayoutOptimization = true: Startup Profiles reorder the launch classes into
//     the first classes.dex (the AGP 8.3+ DEX-layout win, on top of the AOT profile).
// MAINTAINER (v2.0.9): the committed Baseline / Startup Profile must be REGENERATED
// on-device against the v2.0.0 "Timebase" core before the Android release candidate. The
// one-clock scheduler rewrite changed the hot launch + UniFFI-marshalling class set, so a
// stale profile (or the absence of one — none is committed yet) under-optimizes cold start.
// Regeneration needs a device / AVD and CANNOT run on this host CI path:
//   ANDROID_HOME=... ./gradlew :app:generateReleaseBaselineProfile
// then commit the produced baseline-prof.txt under
// :app/src/.../generated/baselineProfiles/. Config/plumbing here targets the v2.0.0 core
// (versionCode/name bumped to 2.0.3 above); only the on-device capture is deferred.
baselineProfile {
    automaticGenerationDuringBuild = false
    dexLayoutOptimization = true
}

// v2.0.1 (ADR 0025): an unflavored `installDebug` convenience alias so the pre-split
// dev/on-device command keeps working after the `distribution` flavor dimension was
// added. Adding a flavor removes the bare `installDebug` task (AGP now names install
// tasks per-variant: `installFossDebug`, `installPlayDebug`, …) — and, unlike
// `assembleDebug` / `bundleRelease`, AGP does NOT create an aggregate `install*`
// anchor. `foss` is the default (`isDefault = true`), so this alias forwards the old
// `installDebug` name to the `foss` variant, leaving the on-device test workflow (and
// any script invoking `installDebug`) undisturbed. The aggregate `assembleDebug` /
// `bundleRelease` anchors AGP still creates (each fans out to every flavor) are left
// as-is — registering our own would collide with them. `afterEvaluate` is required
// because the flavored tasks are created during AGP's variant configuration, which
// runs after this build script's body.
afterEvaluate {
    if (tasks.findByName("installDebug") == null) {
        tasks.findByName("installFossDebug")?.let { fossInstall ->
            tasks.register("installDebug") {
                group = "install"
                description = "Alias for installFossDebug (the default `foss` flavor)."
                dependsOn(fossInstall)
            }
        }
    }
}
